# Generated by Django 5.1 on 2024-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=20)),
                ('generic_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('availablity', models.CharField(max_length=20)),
                ('browser_node', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('reviews', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('deal', models.CharField(max_length=20)),
                ('sold_by', models.CharField(max_length=20)),
                ('buybox', models.CharField(max_length=20)),
                ('image_len', models.CharField(max_length=20)),
                ('main_img_url', models.CharField(max_length=20)),
                ('bullet_point_len', models.CharField(max_length=20)),
                ('bsr1', models.CharField(max_length=20)),
                ('bsr2', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('MRP', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('A_plus', models.CharField(max_length=20)),
                ('store_link', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
